### ISSUE TITLE
Not working with Kubernetes version 1.21

### ISSUE THREAD

**Issue by msvticket** [jenkins-x-charts/vault-instance#10]
When external secrets tries to authenticate with vault it encounters this error and https://github.com/banzaicloud/bank-vaults/issues/1346 logs errors like this:

{"level":50,"time":1630943466645,"pid":17,"hostname":"kubernetes-external-secrets-7686994b8c-ldrwh","payload":{"response":{"statusCode":500,"body":{"errors":["claim \"iss\" is invalid"]}}},"msg":"failure while polling the secret jx/tekton-git"}

I have tried to manually change the vault resource by adding a config element to the kubernetes auth method. Both the following works for me in EKS 1.21:

```
      config:
        disable_iss_validation: true
```

```
      config:
        issuer: kubernetes/serviceaccount
```

Latest version of bank vault should do the latter automatically, so upgrading is probably the best solution. That would mean updating the terraform repos as well.

**Comment by maiakhoa** [comment]
@msvticket where did you add that element to?

**Comment by msvticket** [comment]
Here is an example extract from a vault cr after this change:
```
    externalConfig:
      auth:
      - roles:
        - bound_service_account_names:
          - jx-vault
          - vault-secrets-webhook
          - vault
          - kubernetes-external-secrets
          bound_service_account_namespaces:
          - jx-vault
          - vswh
          - secret-infra
          name: jx-vault
          policies:
          - allow_secrets
          - allow_pki
          ttl: 1h
        type: kubernetes
        config:
          issuer: kubernetes/serviceaccount
```

**Comment by Goodsmileduck** [comment]
Hmm, should we just update the version of bank-vault operator to newest?
defaults.yaml
```
namespace: secret-infra
url: https://banzaicloud.com/docs/bank-vaults/operator/
version: 1.14.3
```

**Comment by msvticket** [comment]
The work around to disable iss validation can be done with this command
kubectl patch --type json -n jx-vault vault vault -p '[
{
    "op" : "add" ,
    "path" : "/spec/externalConfig/auth/0/config",
    "value" :
    {
        "disable_iss_validation": true
    }
}
]'

**Comment by Goodsmileduck** [comment]
I had also to deploy newest chart version, with newer vault version which maiakhoa builded in https://github.com/maiakhoa/vault-instance

here changes:
versionStream/charts/repositories.yaml
```
- prefix: jx-vault
  urls:
  - https://maiakhoa.github.io/vault-instance
```

helmfiles/secret/helmfile.yaml
```
- chart: jx-vault/vault-instance
  version: 1.4.0
  name: vault-instance
  values:
  - jx-values.yaml
  - vault.yaml
```

also had to disable ingress for vault-instance
vault.yaml
```
ingress:
  enabled: false
```
